### ISSUE TITLE
FT Connector/Bridge: could not change unit

### ISSUE THREAD

**Issue by mpacary** [xsericon/vizop-latest#21]
When trying to change the unit of the value field using the dropdown choice widget, nothing happens on the UI and an error appears in console (expected: unit changed)

```
Traceback (most recent call last):
  File ".\ui.py", line 345, in OnIdle
    self.Core.HandleIncomingMessage(Message=self.Core.FromUISocket.recv_string())
  File "C:\...\vizop-latest\heart.py", line 174, in HandleIncomingMessage
    self.HandleChangeElementChoiceRequest(CommandElement=CommandElement, ReturnTopElement=ReturnTopElement,
  File "C:\...\vizop-latest\heart.py", line 484, in HandleChangeElementChoiceRequest
    OldValue = PHAObj.ChangeChoice(Proj=Proj, ElementID=CommandElement.get(info.PHAElementIDTag),
  File "C:\...\vizop-latest\ft_core.py", line 2594, in ChangeChoice
    ValueAttribName='Value', Viewport=ViewportObj)
NameError: name 'ViewportObj' is not defined   
```

Steps to reproduce:
- Open VizopProject13.vp
- Add a Connector/Bridge in column 0
- Try to change the value unit using the dropdown choice, e.g. select "/day"

**Comment by mpacary** [comment]
Connectors/bridges will be removed in a future Vizop version ➡️ should not worth fixing this bug. Closing.
