### ISSUE TITLE
FT Header: could not change operating mode

### ISSUE THREAD

**Issue by mpacary** [xsericon/vizop-latest#22]
* Open project VizopProject13.vp
* In the header element, try to change operating mode, choose "high demand" or "continuous"

Expected: operating mode changed

Observed: no change on UI + Error in console:
```
Traceback (most recent call last):
  File ".\ui.py", line 346, in OnIdle
    self.Core.HandleIncomingMessage(Message=self.Core.FromUISocket.recv_string())   
  File "C:\...\vizop-latest\heart.py", line 174, in HandleIncomingMessage
    self.HandleChangeElementChoiceRequest(CommandElement=CommandElement, ReturnTopElement=ReturnTopElement,
  File "C:\...\vizop-latest\heart.py", line 484, in HandleChangeElementChoiceRequest
    OldValue = PHAObj.ChangeChoice(Proj=Proj, ElementID=CommandElement.get(info.PHAElementIDTag),
  File "C:\...\vizop-latest\ft_core.py", line 2619, in ChangeChoice
    return OldValue
UnboundLocalError: local variable 'OldValue' referenced before assignment
```

**Comment by mpacary** [comment]
Fixed by @pgclarke
