### ISSUE TITLE
closing app: "Address in use" error in console

### ISSUE THREAD

**Issue by mpacary** [xsericon/vizop-latest#5]
Each time I close the app (except by doing it at the splash screen), an error in Python console shows up:

```
Traceback (most recent call last):
  File "vizop.py", line 314, in <module>
    ColScheme=ColourScheme, zmqContext=vizop_misc.zmqContext, DatacoreIsLocal=True)
  File "C:\[...]\Vizop\controlframe.py", line 2862, in __init__
    F2CREPSocket, C2FREQSocket = self.SetupSockets(vizop_misc.RegisterSocket.Register)
  File "C:\[...]\Vizop\controlframe.py", line 2991, in SetupSockets
    SocketLabel='C2FREP', SocketNo=C2FSocketNoToUse, BelongsToDatacore=False, AddToRegister=True)
  File "C:\[...]\Vizop\vizop_misc.py", line 314, in SetupNewSocket
    else: NewSocket.bind("tcp://127.0.0.1:" + str(ThisSocketNo))
  File "zmq\backend\cython\socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq\backend\cython\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
```

**Comment by mpacary** [comment]
Not reproduced on 0.2
