### ISSUE TITLE
new project: frequently, PHA model cannot be selected

### ISSUE THREAD

**Issue by mpacary** [xsericon/vizop-latest#6]
I cannot reproduce this one every time, it appears rather randomy (6 or 7 times out if 10 attempts)

Open the app, start a new project by clicking "**let me try out**", then try to select "**Fault tree | F**" PHA model in the bottom left pane.

First click => "New fault tree created" appears in botton right pane but nothing else happens
At second click => main (edit ?) pane contains the default FT elements OR nothing happens on UI + the following error shows up in console:

```
Traceback (most recent call last):
  File "C:\[...]\Vizop\controlframe.py", line 320, in OnNewPHAModelListbox
self.PHAModelTypesInNameOrder[self.PHAModelsAspect.NewPHAModelTypesList.Widget.GetSelection()])
  File "C:\[...]\Vizop\controlframe.py", line 2250, in DoNewPHAModelCommand
    **AttribDict)
  File "C:\[...]\Vizop\vizop_misc.py", line 221, in SendRequest
    Socket.send(XMLString, copy=True)
  File "C:\[...]\Python37\lib\site-packages\zmq\sugar\socket.py", line 400, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq\backend\cython\socket.pyx", line 728, in zmq.backend.cython.socket.Socket.send
  File "zmq\backend\cython\socket.pyx", line 775, in zmq.backend.cython.socket.Socket.send
  File "zmq\backend\cython\socket.pyx", line 247, in zmq.backend.cython.socket._send_copy
  File "zmq\backend\cython\socket.pyx", line 242, in zmq.backend.cython.socket._send_copy
  File "zmq\backend\cython\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Operation cannot be accomplished in current state
```

At third click (if the error happened): FT elements show up in main pane

**Comment by mpacary** [comment]
Other error I got when clicking on PHA model options :

```
Traceback (most recent call last):
  File "C:\[...]\Vizop\controlframe.py", line 2035, in OnIdle
    MessageReceived = self.CheckForIncomingMessages()
  File "C:\[...]\Vizop\controlframe.py", line 2100, in CheckForIncomingMessages
    MessageReceived |= bool(vizop_misc.ListenToSocket(Socket=ThisSocketObj.Socket, Handler=self.DatacoreHandleRequestFromControlFrame))
  File "C:\[...]\Vizop\vizop_misc.py", line 344, in ListenToSocket
    ReplyXML = Handler(MessageReceived=MessageReceived, **Args)
  File "C:\[...]\Vizop\controlframe.py", line 2189, in DatacoreHandleRequestFromControlFrame
    ReplyXML = Handler(Proj=Proj, XMLRoot=ParsedMsgRoot)
  File "C:\[...]\Vizop\controlframe.py", line 3120, in DatacoreDoNewPHAObj
    NewPHAObj = NewPHAObjType(Proj, **NewPHAObjArgs)
  File "C:\[...]\Vizop\alarmrat.py", line 396, in __init__
    self.PriorityMatrix, self.Urgencies, self.Severities = self.MakeDefaultPriorityMatrix(Priorities=self.Priorities)
  File "C:\[...]\alarmrat.py", line 417, in MakeDefaultPriorityMatrix
    ThisUrgency.MinValue.SetMyValue(MinResponseTime)
AttributeError: 'dict' object has no attribute 'SetMyValue'
```

**Comment by pgclarke** [comment]
These are 2 separate issues. On the first one, I believe it is a screen refresh issue. After clicking Fault Tree to make a new FT, try moving your mouse into the edit panel. You may then see the FT. I have this issue on Mac.
On the second issue, it is one of several problems with the widget handlers. I will clear them one by one. Low priority for now.

**Comment by mpacary** [comment]
Cannot reproduce any of those issues today ➡️ closing
