### ISSUE TITLE
AssertionError when clicking on Event buttons "action" & "parking lot"

### ISSUE THREAD

**Issue by mpacary** [xsericon/vizop-latest#9]
When clicking on "action" or "parking lot" buttons on Events (edit pane), nothing happens on UI and this error appears in console:

```
Traceback (most recent call last):
  File "C:\...\Vizop\controlframe.py", line 2191, in <lambda>
    CanStartDrag=True, CanSelect=True, Mode=NewMode))
  File "C:\...\Vizop\controlframe.py", line 2227, in OnMouseLClickEdit
    CanStartDrag=CanStartDrag, CanSelect=CanSelect, Event=Event)
  File "C:\...\Vizop\faulttree.py", line 6943, in HandleMouseLClick
    self.HandleMouseAnyClick(ClickXInPx, ClickYInPx, TolXInPx, TolYInPx, ClickKind='LeftSingle', **Args)
  File "C:\...\Vizop\faulttree.py", line 6935, in HandleMouseAnyClick
    MouseY=ClickYInPx, **Args)
  File "C:\...\Vizop\faulttree.py", line 246, in HandleMouseLClickOnMe
    PHAObjInControlPanel=self.HostObject.FT, PHAElementInControlPanel=self.HostObject, ComponentInControlPanel=self)
  File "C:\...\Vizop\controlframe.py", line 2303, in GotoControlPanelAspect
    PHAObjInControlPanel=PHAObjInControlPanel, ComponentInControlPanel=ComponentInControlPanel, **Args)
  File "C:\...\Vizop\controlframe.py", line 736, in GotoControlPanelAspect
    self.RedrawControlPanelAspect(Aspect=TargetAspect)
  File "C:\...\Vizop\controlframe.py", line 755, in RedrawControlPanelAspect
    Aspect.Prefill(**Aspect.CurrentArgs)
  File "C:\...\Vizop\controlframe.py", line 2030, in Prefill
    self.PrefillMethod(**Args)
  File "C:\...\Vizop\controlframe.py", line 1801, in <lambda>
    PrefillMethod=lambda **Args: self.PrefillWidgetsForAssociatedTextAspect(Aspect=NewAspect, **Args),
  File "C:\...\Vizop\controlframe.py", line 1959, in PrefillWidgetsForAssociatedTextAspect
    NotebookPage=Aspect.NotebookPage, Aspect=Aspect)
  File "C:\...\Vizop\controlframe.py", line 1893, in LineupVariableWidgetsForAssociatedTextAspect
    assert hasattr(TargetElement, AssociatedTextNumberingListAttrib)
```

**Comment by mpacary** [comment]
Not reproduced on 0.2
